version: '3.8'

services:
  vacation-bot:
    build: .
    container_name: vacation-bot-container
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  vacation-bot-data: